#!/usr/bin/env bash

################################################################
#                                                              #
#  Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>  #
#                                   						   #
#  Reconfigured For Exodia OS                                  #
#                                   						   #
#  @author      : 00xWolf           						   #
#    GitHub    : @mmsaeed509       						   #
#    Developer : Mahmoud Mohamed   						   #
#  﫥  Copyright : Exodia OS        						    #
#                                   						   #
################################################################

# Current Theme #
dir="$HOME/.config/bspwm/rofi/themes"
theme="${dir}/powermenu"

# Theme Elements #
prompt="`hostname`"
mesg="See you Aziz \nUptime : `uptime -p | sed -e 's/up //g'`"

list_col='1'
list_row='7'

# Options #
option_1=" Shutdown"
option_2=" Suspend"
option_3=" Reboot"
option_4=" Hibernate"
option_5=" Lock"
option_6=" Logout"
yes='✔ Yes'
no='✘ No'

# Rofi CMD #
rofi_cmd() {

    echo -e "${option_1}\n${option_2}\n${option_3}\n${option_4}\n${option_5}\n${option_6}\n${mesg}" |
        rofi -theme-str "listview {columns: $list_col; lines: $list_row;}" \
             -dmenu \
             -p "$prompt" \
             -markup-rows \
             -theme ${theme}

}

# Pass variables to rofi dmenu #
run_rofi() {

	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | rofi_cmd
}


# Confirmation CMD #
confirm_cmd() {

	rofi -theme-str 'window {location: center; anchor: center; fullscreen: false; width: 350px; height: 170;}' \
		 -theme-str 'mainbox {orientation: vertical; children: [ "message", "listview" ];}' \
		 -theme-str 'listview {columns: 2; lines: 1;}' \
		 -theme-str 'element-text {horizontal-align: 0.5;}' \
		 -theme-str 'textbox {horizontal-align: 0.5;}' \
		 -dmenu \
		 -p 'Confirmation' \
		 -mesg 'Are you Sure?' \
		 -theme ${theme}

}

# Ask for confirmation #
confirm_exit() {

	echo -e "$yes\n$no" | confirm_cmd

}

# Confirm and execute #
confirm_run () {

	selected="$yes"

#	if [[ "$selected" == "$yes" ]];
	if [[ "$selected" == "$yes" ]];
		
		then
        	
			${1} && ${2} && ${3}
    else

        exit

    fi

}

# Execute Command #
run_cmd() {

if [[ "$1" == '--opt1' ]];
		
		then
			
			confirm_run 'systemctl poweroff'

 	elif [[ "$1" == '--opt2' ]];
		
		then
			
			confirm_run 'mpc -q pause' 'betterlockscreen -l' 'systemctl suspend' 

 	elif [[ "$1" == '--opt3' ]];
		
		then

			confirm_run 'systemctl reboot'

  	elif [[ "$1" == '--opt4' ]];
		
		then
			
			confirm_run 'systemctl hibernate'

  elif [[ "$1" == '--opt5' ]];
		
		then
			betterlockscreen -l

	elif [[ "$1" == '--opt6' ]];
		
		then
			
			confirm_run 'kill -9 -1'
			
	fi
}

# Actions #
chosen="$(run_rofi)"
case ${chosen} in
    $option_1)
		run_cmd --opt1
        ;;
    $option_2)
		run_cmd --opt2
        ;;
    $option_3)
		run_cmd --opt3
        ;;
    $option_4)
		run_cmd --opt4
        ;;
    $option_5)
		run_cmd --opt5
        ;;
    $option_6)
		run_cmd --opt6
        ;;
esac

